version: '3.8'
services:
  database:
    image: postgres:13.2-alpine
    container_name: astray-database
    restart: always
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: astray-app
    container_name: astray-app
    command: node dist/index.js
    ports:
      - 29115:29115
    volumes:
      - ./logs:/app/logs
    environment:
      NODE_ENV: production
      PORT: 29115
    env_file:
      - .env
    depends_on:
      - database
volumes:
  database:
    name: astray-database
networks:
  default:
    name: astray-default
